### ISSUE TITLE
Crashes VS 2022 Ver 17.3.2

### ISSUE THREAD

**Issue by r14958** [odalet/VSWebBrowserExtension#2]
I am using Visual Studio Community Edition version 17.3.2.  Installation from VS Marketplace went smoothly, but when I select View --> Other Windows --> Web Browser, a floating browser window does appear, but then VS 2022 locks up and crashes.

**Comment by odalet** [comment]
Hi, I've tried to reproduce your issue on a fresh install of VS2022 Community Edition (v17.3.3 though) on my Windows 11 laptop, and... everything works fine.

I've just published a new version of the extension. Maybe you could try to update to this version. This version allows to define the default Home Page, but it also provides logging. So, if you still encounter issues, could you:

After you've updated to the latest version of the extension,

* In Tools > Options > Web Browser > General, set the log level to Verbose
* Activate the Output Window and choose "Web Browser Extension" in the drop-down
* Try to close/reopen Visual Studio and see if errors appear in the Output window.

![image](https://user-images.githubusercontent.com/79333/188322906-6c088d4e-4d42-4083-8c2e-f45ced55baad.png)

Could you also open a cmd prompt and type 

```cmd
"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe" /log c:\temp\vslog.xml
```

Then upload `vslog.xml` here?

**Comment by r14958** [comment]
Hello odal;et,

I upgrade my VS Comm Edition to 17.3.3 and installed VSWebBrowser ver. 0.2.0.  Setting the Web Browser logging to verbose.  I saw this message in the Output window:
22:24:45.730 [Debug]  WebBrowserOptionsPage: LoadSettingFromStorage().

When I fired up the Web Browser window, VS crashed again with no additional messages showing up in the Output Window.  I have uploaded the xml log as you requested.  Let me know if you need any other info.
[vslog.zip](https://github.com/odalet/VSWebBrowserExtension/files/9523097/vslog.zip)

**Comment by odalet** [comment]
Hi, sorry for the delay, I was a bit sick last week.

Now, I've skimmed through the log file you provided and... unfortunately, it was not of much help. Apart from noticing the extension settings were not saved by Visual Studio (weird), I didn't see anything explaining your crash.

So, I'll have to throw a bunch of questions to you:

* What is the exact version of Windows you are running (in a command prompt, type `ver`)?
* Do you have Admin rights on the machine?
* I assume you have the Edge browser installed on your system, but what version is it?
  * Open Edge, go to the "..." button on the top right, then "Help and feedback", then  "About Microsoft Edge", you should get something like that:
  
![image](https://user-images.githubusercontent.com/79333/190863408-32a9e1bd-c0f9-4167-a91f-3806fcc04eae.png)

Now, some more tests you can try:

* Run VS, change the log settings to Verbose (or ensure they are indeed set to Verbose), close VS (that should make sure the log settings are saved)
* Open VS again, try the Web Browser and see if some more logs appear
* Open VS as an Administrator, and try the Web Browser

And, lastly, I crafted a stand-alone version of the Web Browser (so that I can get VS out of the picture... or not). You'll find attached a WPF application that embeds the Edge Browser control in pretty much the same way as the extension does. 

Can you run it, play a bit with it and, even if everything went well, send me back the log file it should have produced in `C:\ProgramData\MiniBrowser\log\minibrowser.log`

[minibrowser.zip](https://github.com/odalet/VSWebBrowserExtension/files/9591990/minibrowser.zip)

NB: There's nothing secret in this test application: you can have a look at its source code [here](https://github.com/odalet/VSWebBrowserExtension/tree/master/src/MiniBrowser) if you wish

**Comment by r14958** [comment]
Hello odalet,  I really appreciate the time and effort you have put into responding to my bug report.  I will check out your recommendations and report back ASAP.

**Comment by odalet** [comment]
I've just uploaded version 0.3.0 of the extension, because I've updated the browser component and changed a bit the way I use it, it might by chance solve your issues. Keep me informed!
