### ISSUE TITLE
Is it possible to open multiple instances? 

### ISSUE THREAD

**Issue by DevenKShah** [odalet/VSWebBrowserExtension#6]
Also can the links be actioned with in the window instead of new external window?

**Comment by odalet** [comment]
Multiple instances should be doable although I'm not sure it is desirable: I think that if you need tabs navigation, you'd rather open a real browser: after all, I don't plan on making this extension into a full-featured browser.

As for preventing external windows from opening on clicks, this is something I had a quick look into as I also find it a bit bothering : see issue #4 (from me to myself). I didn't succeed though. I guess having this work would imply dynamically rewriting the current page's HTML in order to force the target location of the link to be the current window... 

I currently don't have the bandwidth (nor motivation to be honest) for working on those topics. Pull Requests are welcome though!
