### ISSUE TITLE
iframe

### ISSUE THREAD

**Issue by beyaz** [odalet/VSWebBrowserExtension#8]
net::ERR_CONTENT_DECODING_FAILED

Server is .net core web api.
Sometimes i m taking this error.

when this line  app.UseResponseCompression();
then error fixed.

how can fix this issue ?

**Comment by odalet** [comment]
Hi!

I'm afraid I don't understand what your problem is and will need further information if I'm to help you:

* `net::ERR_CONTENT_DECODING_FAILED`: where do you see this error? Can you provide logs or screenshots?
* Title of the issue: `iframe`??? If you are running a Web Api project, what do you need and iframe for? 
* `app.UseResponseCompression();`: I guess this is something you added to your project in order for the issue to go away, however this should have nothing to do with how the browser reacts (with or without compression of the responses, browsers should be able to render those responses, and I'm only wrapping the Edge browser in this VS plugin...)

Then, 

* What happens if you use another standalone browser to consume your API (say Chrome, Firefox or Edge)?
* Do you have an example repository I could clone to try to reproduce your issue, or better, a URL that exhibits the same issue?

Regards

**Comment by odalet** [comment]
No news... closing this
